modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
    modId="ad_astra_giselle_addon"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_homepage}"
    authors="gisellevonbingen"
    logoFile="icon.png"
    description='''${mod_description}'''

[[dependencies.ad_astra_giselle_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ad_astra_giselle_addon]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_api_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ad_astra_giselle_addon]]
    modId="botarium"
    mandatory=true
    versionRange="[${botarium_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ad_astra_giselle_addon]]
    modId="ad_astra"
    mandatory=true
    versionRange="[${ad_astra_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ad_astra_giselle_addon]]
    modId="resourcefulconfig"
    mandatory=true
    versionRange="[${resourcefulconfig_version},)"
    ordering="AFTER"
    side="BOTH"
    