modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="MIT"
issueTrackerURL="https://github.com/gisellevonbingen/Minecraft-Ad-Astra-Giselle-Addon/issues"

[[mods]]
    modId="ad_astra_giselle_addon"
    version="${mod_version}"
    displayName="Ad Astra: Giselle Addon"
    displayURL=""
    authors="gisellevonbingen"
    description='''Just add good things in my think for Ad Astra'''
    itemIcon="ad_astra_giselle_addon:oxygen_can" #for Catalogue

[[dependencies.ad_astra_giselle_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.ad_astra_giselle_addon]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ad_astra_giselle_addon]]
    modId="ad_astra"
    mandatory=true
    versionRange="[${ad_astra_version},)"
    ordering="AFTER"
    side="BOTH"
