// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

// Mod
archives_base_name=Ad-Astra-Giselle-Addon
maven_group=gisellevonbingen.ad_astra_giselle_addon
mod_id=ad_astra_giselle_addon
mod_version=8.2
mod_name=Ad Astra: Giselle Addon
mod_description=Just add good things in my think for Ad Astra
mod_license=MIT
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon
mod_source=https://github.com/gisellevonbingen/Minecraft-Ad-Astra-Giselle-Addon
mod_issues=https://github.com/gisellevonbingen/Minecraft-Ad-Astra-Giselle-Addon/issues

// Minecraft, Mod Loader
mc_version=1.21.1
fabric_loader_version=0.19.2
fabric_api_version=0.116.9
neoforge_loader_version=4
neoforge_api_version=21.1.229
neoforge_api_version_range=[21.1.229,)
fabric_parchment_version=2024.11.17
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.sourcesets.enabled=false

// Ad Astra - Required
csl_version=0.0.10
ad_astra_version=1.16.19
ad_astra_fabric_file=8758529
ad_astra_neoforge_file=8758526
resourcefullib_version=3.0.12
resourcefulconfig_version=3.0.11

// Ad Astra - Override

// Ad Astra - Optional
architectury_version=13.0.11
cloth_config_version=15.0.140
jei_version=19.27.0.340
rei_version=16.0.799
patchouli_version=78

// Common - Implementation

// Common - Runtime Only
