// Forge - Implementation
curios_file=4731891
mekanism_version=10.4.0.14
pneumaticcraft_repressurized_file=4692368
create_version=6.0.6-150
flywheel_version=1.0.4
registrate_version=MC1.20-1.3.3
ponder_version=1.0.80
mantle_file=6258424
tinkersconstruct_file=6266282

// Forge - Runtime Only
top_file=4579432
jade_file=4573193
refined_storage_file=4623636
